networks: 
  cassandra: 
services: 
  cassandra1: 
    image: cassandra:5.0.2 
    container_name: cassandra1 
    hostname: cassandra1 
    networks:
      - cassandra 
    ports:
      - "9042:9042" 
    volumes: 
      - ./datadir/cassandra1:/var/lib/cassandra 
    environment: &environment 
        CASSANDRA_SEEDS: "cassandra1,cassandra2" 
        CASSANDRA_CLUSTER_NAME: ExampleCluster 
        CASSANDRA_DC: DC1 
        CASSANDRA_RACK: RACK1 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
        CASSANDRA_NUM_TOKENS: 8
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10     
  
  cassandra2: 
    image: cassandra:5.0.2 
    container_name: cassandra2 
    hostname: cassandra2 
    networks: 
      - cassandra 
    ports: 
      - "9043:9042" 
    volumes: 
      - ./datadir/cassandra2:/var/lib/cassandra 
    environment: *environment 
    depends_on: 
      cassandra1: 
        condition: service_started
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
  
  cassandra3: 
    image: cassandra:5.0.2 
    container_name: cassandra3 
    hostname: cassandra3 
    networks: 
      - cassandra 
    ports: 
      - "9044:9042" 
    volumes: 
      - ./datadir/cassandra3:/var/lib/cassandra 
    environment: *environment 
    depends_on: 
      cassandra2: 
        condition: service_started
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
  
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:5.0.2
    networks: 
      - cassandra 
    depends_on:
      cassandra1:
        condition: service_healthy
      cassandra2:
        condition: service_healthy
      cassandra3:
        condition: service_healthy  
    volumes:
      - ./init.cql:/schema.cql
    command: /bin/bash -c "cqlsh cassandra1 -f /schema.cql"